name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
          registry-url: https://registry.npmjs.org/
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run dnt 🛠️ 
        run: deno task dnt
      - name: Publish package on NPM 📦
        working-directory: ./npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
